[package]
name = "feature_profile"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
# specta removed
tauri = { version = "^2.0.0", features = [] }
shared_db = { path = "../shared_db" }
