[package]
name = "irongraph_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
specta = { version = "=2.0.0-rc.22", features = ["serde"] }
schemars = "0.8"
